version: '3.2'
services:
    php:
        build: ./php/
        volumes:
          - ./php/log:/var/log/php_log
          - ./laravel:/var/www/html
          - ./php/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
          - ./php/php-fpm/api.conf:/usr/local/etc/php-fpm.d/api.conf
        links:
          - postgres
          - redis
        environment:
          XDEBUG_CONFIG: "remote_host=10.254.254.254 idekey=laravelTest remote_enable=1 remote_handler=dbgp remote_port=9000 remote_autostart=1 remote_connect_back=0 remote_log=/var/log/php_log/xdebug.log"
          PHP_IDE_CONFIG: "serverName=laravel.test.com"
        restart: always
    nginx:
        build: ./nginx/
        volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d
          - ./nginx/log:/var/log/nginx
          - ./laravel:/var/www/html
        links:
          - php
        ports:
          - 8888:80
        restart: always
    postgres:
        build: ./postgres/
        volumes:
          - ./postgres/postgres-data:/var/lib/postgresql/data
        environment:
          - POSTGRES_PASSWORD=asfJFIOMioasjiIOJFDSJFS8923JIO
          - POSTGRES_USER=laravel
          - POSTGRES_DB=laravel
        ports:
          - 5555:5432
        restart: always
    redis:
        build: ./redis/
        ports:
          - 6666:6379
        restart: always
